### ISSUE TITLE
Is RSTAN available for Hamiltonian Monte Carlo based BSEM measurement invariance testing for multiple-group factor mean comparisons?

### ISSUE THREAD

**Issue by wencong002** [stan-dev/rstan#1146]
#### Summary:
Please provide a short summary (no more than a sentence or two).
Is RSTAN available for Hamiltonian Monte Carlo based BSEM measurement invariance testing for multiple-group factor mean comparisons?

#### Description:
Describe the issue as clearly as possible.
We are now doing a comparative study regarding Bayesian Structural Equation Model, aligned-Exploratory Structural Equation Model and penalized alignment when they establish measurement invariance. As we know that HMC algorithm based Bayesian analysis have better convergence. We have an idea that we use HMC based BSEM multiple-group analysis to generate and analyze data in such a monte carlo comparative study. But as I am new to RSTAN, I cannot find any information about HMC's application to BSEM and measurement invariance testing. Thanks in advance!

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.

#### Current Output:
If applicable, any relevant output from RStan.

#### Expected Output:
If applicable, the output you expected from RStan.

#### RStan Version:
The version of RStan you are running (e.g., from `packageVersion("rstan")`)

#### R Version:
The version of R you are running (e.g., from `R.version.string`)

#### Operating System:
Your operating system (e.g., OS X 10.11.3)

**Comment by bob-carpenter** [comment]
Hi, @wencong002:  This is the issue tracker for bugs and feature requests for RStan.  Given that you're instead asking a question about modeling, the best place to do that is on our forums:

https://discourse.mc-stan.org

The answer is that SEM is just notation for likelihoods, so if you can work out your likelihood and come up with sensible priors that involve only continuous parameters, then you can convert SEM notation to Stan notation.  The closest thing we have to this is a case study on using the package `blavaan`, which is backed by Stan:

https://mc-stan.org/users/documentation/case-studies/sem.html

I'd suggest looking into CmdStanR rather than RStan as it's easier to install and it keeps up with improvements in Stan.  RStan is blocked by the restrictive CRAN policies, which make it very hard to update.

You could also fit this model with PyMC and it looks like they also have some tutorials around SEM.

**Comment by bob-carpenter** [comment]
This is off topic for the issue tracker, so I'm closing.  Please follow up on the forums if there are more questions as that's the better venue for this kind of thing---only our devs tend to read the issue trackers.

**Comment by wencong002** [comment]
Thanks for your enthusiastic replies. Really appreciate your support. I have already signed up in stan forum. Thank you!
