### ISSUE TITLE
API for extracting convergence information

### ISSUE THREAD

**Issue by tpapp** [stan-dev/rstan#116]
It would be great if `rstan` had a standardized API for extracting convergence and sample size information from `stanfit` objects. The functionality is there, but user implementations are necessarily a bit _ad hoc_ (see functions below) and use undocumented internals.

The following are toy implementations (I am not an S4 wizard and I know very little about `rstan` internals, just to demonstrate what I would like to have and how I am doing it currently):

``` R
Rhat <- function(fit) {
  summary(fit)$summary[,"Rhat"]
}

n_eff <- function(fit) {
  summary(fit)$summary[,"n_eff"]
}

sample_size <- function(fit) {
  length(extract(fit, pars = "lp__")[[1]])
}
```

Then the user could eyeball plots like

``` R
hist(Rhat(fit))
hist(n_eff(fit)/sample_size(fit))
```

to detect convergence problems, or do things like

``` R
Rh <- Rhat(fit)
Rh[Rh > 1.1]
```

for the latter it is very useful that the implementation above provides the names of variables as labels for the vector.

**Comment by jgabry** [comment]
I'm closing this since the plan for moving to reference classes soon(ish) is now in place 

https://github.com/stan-dev/stan/wiki/User-Interface-Guidelines-for-Developers 

and I don't think we'll need to define any S3 or S4 methods like the ones proposed here to make the API consistent once that happens.
