### ISSUE TITLE
Cannot install in Windows 7

### ISSUE THREAD

**Issue by ignacio82** [stan-dev/rstan#150]
I'm trying to install RStan by running:

```
Sys.setenv(MAKEFLAGS = "-j4") 
source('http://mc-stan.org/rstan/install.R', echo = TRUE, max.deparse.length = 2000)
install_rstan()
```

This is the error that I get in my Windows 7 computer:

```
Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! Warning message:
running command 'make -f "C:/Users/IMARTI~1/DOCUME~1/R/R-31~1.2/etc/x64/Makeconf" -f "C:/Users/IMARTI~1/DOCUME~1/R/R-31~1.2/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="file1a7843c04c77.dll" WIN=64 TCLBIN=64 OBJECTS="file1a7843c04c77.o"' had status 127 In addition: Warning messages:
1: package ‘inline’ was built under R version 3.1.3 
2: running command 'C:/Users/IMARTI~1/DOCUME~1/R/R-31~1.2/bin/x64/R CMD SHLIB file1a7843c04c77.cpp 2> file1a7843c04c77.cpp.err.txt' had status 1 
```

Thanks for the help!

**Comment by bob-carpenter** [comment]
Do you have Rtools installed for the C++ toolchain?  If not, see

https://github.com/stan-dev/rstan/wiki/Install-Rtools-for-Windows

and if so, did you follow the instructions so that g++ and make
can be called from R?

If that's all OK, could you install Rcpp successfully?  We used
to have a test to see if Rcpp and inline were installed OK,
but that seems to have disappeared.

Finally, did you make sure to restart R?
- Bob

**Comment by ignacio82** [comment]
installing Rtools did the trick. Thanks!
