### ISSUE TITLE
Multiple Error messages displaying together/overlapping when running multiple chains

### ISSUE THREAD

**Issue by davidmanheim** [stan-dev/rstan#245]
When running a bunch of chains from the terminal via a script, it displays the errors all at the end, together. Running R 3.1.2, RStan 2.8.2, with 5 chains, it looks like all 5 warnings are racing to display together, so the characters output alternate strangely, mangling the output. As you can see below, this has an impact on intelligibility of the error messages. (This seems to be a "compiled under different version of R" error.)

![image](https://cloud.githubusercontent.com/assets/1664046/11940967/0106943a-a7e1-11e5-9ebd-80367eaba52b.png)

**Comment by bob-carpenter** [comment]
32-bit Windows R terminal?

The only solution would be to synchronize the outputs so that each error is printed atomically.  But I'm not sure that's easy or even possible the way R runs multiple processes for parallelization.  

Generally, we recommend debugging on a single chain then running in silent (quiet?) mode.  Does that still dump errors at the end in a meaningful way?

**Comment by davidmanheim** [comment]
The errors for running under a different version of R than the package was compiled under still appear, clearly, using only 1 chain - I'm more concerned that I simply can't tell if there is another error message buried in this output.

**Comment by davidmanheim** [comment]
I'm closing this - it's an issue with anything outputting to the Windows terminal, which isn't within scope to fix ;)
