### ISSUE TITLE
missing newline for # sign in iteration output

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/rstan#282]
You can see that the # sign after iteration 10000 should go on the next line (or you should get rid of these # signs altogether --- I don't know what they're there for):

```
Chain 3, Iteration: 9000 / 10000 [ 90%]  (Sampling)
Chain 3, Iteration: 10000 / 10000 [100%]  (Sampling)# 
#  Elapsed Time: 0.036745 seconds (Warm-up)
#                0.024787 seconds (Sampling)
#                0.061532 seconds (Total)
```

For:  rstan (Version 2.9.0, packaged: 2016-01-05 16:17:47 UTC, GitRev: 05c3d0058b6a)

**Comment by andrewgelman** [comment]
Hi, let me take this as a reminder that we should be cleaning up the Stan output.  When I run Stan from R it fills up the console with these messages, it’s quite annoying and also who needs to see every tenth, anyway.  We can discuss sometime at Stan meeting.  My suggestion from before, which I still like, is to just spit out one message after 10% of warmup iterations giving estimated total time, maybe another after 10% of the sampling iterations with an updated estimated time, since they can be faster than warmup.  Also we should have a no-print option, I think.
A

**Comment by jgabry** [comment]
This was fixed a while ago but I guess we forgot to close the issue.
