### ISSUE TITLE
diagnostics fail on one-chain models

### ISSUE THREAD

**Issue by infotroph** [stan-dev/rstan#290]
#### Summary:

When a model contains only one chain, some diagnostic plots fail with dimensionality errors.
#### Description:

For models that only contain one chain, `stan_diag()` and `stan_par()` both fail with errors that boil down to "this input isn't a matrix." I suspect they all share the underlying cause that `extract(model, par, permuted=FALSE)` returns a vector instead of an array from these models — is that the intended behavior?

If the `extract()` behavior needs changing, I should probably leave it to the experts. If the fix is to make the plotting commands handle vectors, I'm happy to take a stab at a PR — perhaps wrap `as.array` around the `extract(...)` calls in `stan_sample`, `stan_stepsize`, `stan_treedepth`, `stan_divergence` and `stan_par`? Others seem to behave OK with single chains.
#### Reproducible Steps:

``` R
library(rstan)
set.seed(42)

mod <- "
data{ int N; real x[N]; }
parameters{ real mu; real<lower=0> sig; }
model{ x ~ normal(mu, sig); }
"

data <- list(N=100, x=rnorm(100))

fit1 <- stan(model_code=mod, data=data, chains=1)
fit2 <- stan(model_code=mod, data=data, chains=2)

# Errors: 
stan_diag(fit1)
stan_diag(fit1, information="divergence")
stan_par(fit1, par="mu")

# OK: 
stan_diag(fit2)
stan_diag(fit2, information="divergence")
stan_par(fit2, par="mu")
```
#### Current Output:

```
> stan_diag(fit1)
Error in 1:nrow(lp) : argument of length 0
> stan_diag(fit1, information="divergence")
Error in do.call("c", sp) : second argument must be a list
> stan_par(fit1, par="mu")
Error in apply(treedepth, 2L, function(y) as.numeric(y == max_td)) : 
  dim(X) must have a positive length
```
#### Expected Output:

(diagnostic plots with no error messages)
#### RStan Version:

```
Package: rstan
Type: Package
Title: R Interface to Stan
Version: 2.9.0-3
Date: 2016-02-11
<...snip...>
Built: R 3.2.3; x86_64-apple-darwin13.4.0; 2016-04-18 18:28:56 UTC; unix
<...snip...>
GithubRef: develop
GithubSHA1: 51ccb90e8225b3b3bb3abfb43c50bf27e261fd22
GithubSubdir: rstan/rstan
```
#### Session Info:

```
R version 3.2.3 (2015-12-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.3 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rstan_2.9.0-3   ggplot2_2.1.0   devtools_1.10.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.3      codetools_0.2-14 digest_0.6.9     withr_1.0.1      grid_3.2.3      
 [6] R6_2.1.2         plyr_1.8.3       gtable_0.2.0     stats4_3.2.3     git2r_0.13.1    
[11] scales_0.4.0     httr_1.1.0       curl_0.9.6       labeling_0.3     tools_3.2.3     
[16] munsell_0.4.3    inline_0.3.14    colorspace_1.2-6 memoise_1.0.0    gridExtra_2.2.1 
```

**Comment by bob-carpenter** [comment]
Although I believe this is a "feature", not a "bug", I also find it very confusing and wished there were default values that worked OK in these settings.  The problem is that pairs is trying to contrast the behavior across chains (which I also find confusing).  Anyway, just letting you know the behavior probably won't change.  

What should happen, though, is that there should be better warnings when those inputs arise so we don't continue to get emails and issue reports.

**Comment by infotroph** [comment]
I hope this isn't getting too far afield, but in that case I'm curious what the best practice is for diagnostics. My current application is a model with persistent divergence warnings and periodically stuck chains, which I thought I had gathered was a case where I'd want to run a single chain, examine par-vs-accept, and fix the model to make one chain look good before I worry about convergence/parallelism. Is that not the case, or are you just saying single chains call for different plotting methods?

**Comment by bob-carpenter** [comment]
Issue reports should stick to the issues, not devolve into general
discussions of statistical practice.  If it's not ready to be
crisply laid out as an issue, it doesn't belong in the issue tracker.
The original report is fine, but this question should go on the stan-users
mailing list.  I'll cut and respond there.

**Comment by jgabry** [comment]
Thanks for reporting this. I guess it's not wrong to create the diagnostic plots for only one chain but they'll be more useful with multiple chains. For now I've changed it (in 99104a5) so that there's actually an informative message along with the error if there's only a single chain. I have a few other comments but they're more appropriate on stan-users so I'll respond to Bob's post there.

**Comment by jgabry** [comment]
> I have a few other comments but they're more appropriate on stan-users so I'll respond to Bob's post there.

Never mind, Bob already said everything I was thinking.

**Comment by jgabry** [comment]
For two (related) reasons I think for now we should just keep the informative messages (added in 99104a5) and require at least 2 chains (just for these `stan_diag` and `stan_par` functions): 
1. I can't think of a reason to make those plots only with a single chain when it doesn't take longer to run multiple chains (in parallel) 
2. Since there's no advantage to running one chain, I'd prefer not to complicate the code further in order to handle that case. It wouldn't be hard to do, but it seems unnecessary. 

If anyone disagrees and feels strongly about it then we can definitely reopen this and add the functionality for models with just a single chain.

**Comment by betanalpha** [comment]
When diagnosing divergences it’s the _shape_ of the posterior that
matters

**Comment by betanalpha** [comment]
Whoops.  Meant to say,

When diagnosing divergences it’s the _shape_ of the posterior that
matters, and the shape is revealed regardless of how many chains
are run.  More chains can cover more pathological regions of the
posterior and hence yield more accurate diagnostics, but it’s not
necessary as you have to fix the pathologies found by a single
chain anyways.

**Comment by jgabry** [comment]
Thanks Michael, good point. I guess I should get these working with one
chain too. Shouldn't be difficult.
