### ISSUE TITLE
append_samples undocumented

### ISSUE THREAD

**Issue by mike-lawrence** [stan-dev/rstan#311]
The "append_samples" argument to rstan::stan() appears to be undocumented; at least, it's mentioned as existing but the docs don't indicate what it does or its default. (Path to pertinent doc: rstan/rstan/rstan/man/stan.Rd)

**Comment by jgabry** [comment]
Thanks for pointing this out. I'll add it to the documentation. 

`append_samples` is only relevant if `sample_file` is specified. If `sample_file = posterior.csv` and `posterior.csv` exists then setting `append_samples = TRUE` will append the samples to the existing `posterior.csv` instead of overwriting it.
