### ISSUE TITLE
Floating point exception 8 crashes R

### ISSUE THREAD

**Issue by davharris** [stan-dev/rstan#316]
#### Summary:

If Stan returns floating point exception 8, R says `Floating point exception: 8` and exits
#### Reproducible Steps:

```
library(rstan)

mc <- '
parameters {real theta;}
model {
  target += 1/0;
}
'
sm <- stan_model(model_code = mc)
post <- sampling(sm, show_messages = FALSE)
```
#### Current Output:

```
SAMPLING FOR MODEL '914b207aecf5601cf891596bf3ad3cc7' NOW (CHAIN 1).
Floating point exception: 8
```
#### Expected Output:

An informative error message (e.g. "division by zero error"). 
#### RStan Version:

2.10.1
#### R Version:

R version 3.3.1 (2016-06-21)
#### Operating System:

OS X 10.11.6

**Comment by bob-carpenter** [comment]
Thanks for the report.  I verified with RStan 2.10 on Mac OSX; the behavior is the same without `show_messages = FALSE`. 

Integer division by zero is undefined in C++, so the right way to deal with this in a program where there might be division by zero is to check whether the denominator is zero.  We can't check that internally, because the branching would be very slow.  Switching the integers `1 / 0` to reals `1.0 / 0.0` has the expected behavior of rejecting the initial values (no way to get a finite density).

RStan shouldn't crash R no matter what happens, so we need to figure out what's happening and try to catch whatever error's being thrown.

**Comment by davharris** [comment]
Thanks Bob! Looks floating point exception 8 crashes a lot of programs, [including other R packages](https://stackoverflow.com/questions/37617749/r-floating-point-exception-8-with-caret-and-rbf).

**Comment by bgoodri** [comment]
We'll fix this upstream in Stan.

**Comment by syclik** [comment]
Yes. I just found out what's causing the behavior and it's definitely in
Stan.
