### ISSUE TITLE
rstan package ist not installed after successful compilation

### ISSUE THREAD

**Issue by MattRoess** [stan-dev/rstan#39]
I am using a MacPro with 10.9.1 running and the latest version of R. I tried to install the rstan package how it has been described. It worked fine until the following messages

installing via 'install.libs.R' to /Library/Frameworks/R.framework/Versions/3.0/Resources/library/rstan
installing rstan libs to /Library/Frameworks/R.framework/Versions/3.0/Resources/library/rstan/libs
installing libstan.a to /Library/Frameworks/R.framework/Versions/3.0/Resources/library/rstan/libstan
*\* R
*\* inst
*\* preparing package for lazy loading
*\* help
**\* installing help indices
*\* building package indices
*\* installing vignettes
*\* testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  kann shared object '/Library/Frameworks/R.framework/Versions/3.0/Resources/library/rstan/libs/rstan.so' nicht laden:
  dlopen(/Library/Frameworks/R.framework/Versions/3.0/Resources/library/rstan/libs/rstan.so, 6): Symbol not found: __ZNK4Rcpp7RObject4attrERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE
  Referenced from: /Library/Frameworks/R.framework/Versions/3.0/Resources/library/rstan/libs/rstan.so
  Expected in: flat namespace
 in /Library/Frameworks/R.framework/Versions/3.0/Resources/library/rstan/libs/rstan.so
Fehler: Laden fehlgeschlagen
Ausführung angehalten
ERROR: loading failed
- removing ‘/Library/Frameworks/R.framework/Versions/3.0/Resources/library/rstan’

Die heruntergeladenen Quellpakete sind in 
    ‘/private/var/folders/4j/wt_djlx914n1hhl9jpsc7gq40000gn/T/RtmpGvUg5W/downloaded_packages’
Warnmeldung:
In install.packages("rstan", type = "source") :
  Installation des Pakets ‘rstan’ hatte Exit-Status ungleich 0

**Comment by bbolker** [comment]
Hmm.  I'm getting a similar problem on Ubuntu 14.04, installing rstan on R-devel (3.3.0) immediately after a successful Rcpp (0.12.2)/BH/StanHeaders install ... this is with g++ 4.8.4 ...

The final error is

```
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/usr/local/lib/R/site-library/rstan/libs/rstan.so':
  /usr/local/lib/R/site-library/rstan/libs/rstan.so: undefined symbol: _ZN4stan4lang15indexes_grammarIN5boost6spirit17line_pos_iteratorIN9__gnu_cxx17__normal_iteratorIPKcSsEEEEEC1ERNS0_12variable_mapERSt18basic_stringstreamIcSt11char_traitsIcESaIcEERNS0_18expression_grammarISA_EE
```

I will keep banging on this and see if I can make any headway, but any suggestions will be appreciated.

**Comment by bob-carpenter** [comment]
@bbolker :  Thanks for reporting.  Unfortunately, this issue is closed, so it's not the best place for comments.

Several other people reported this on the mailing list and @bgoodri wrote back:

<blockquote>
I am guessing you have StanHeaders 2.9.0 installed which will be out of sync for a day or two with rstan.
</blockquote>

**Comment by bbolker** [comment]
Thanks & sorry for inappropriate venue ... didn't realize I had jumped into the middle of a release process. Could you possibly point me to the appropriate mailing list venue for reading the rest of the comment/suggestions about what to do if I'm impatient?  I've been googling around/looking at https://groups.google.com/forum/#!forum/stan-users but can't find it ...

For what it's worth `devtools::install_version("StanHeaders","2.8.0"); install_packages("rstan")` worked like a charm.

**Comment by bgoodri** [comment]
rstan should be on CRAN this afternoon, but the instructions at the bottom
of

http://mc-stan.org/misc/nips.html

should still work if you are not using Windows. It also has instructions on
how to install the rstanarm package, which we will release on CRAN later
this week but it might be of particular interest to you because its
stan_glmer() function uses the lme4 parser to make the X and Z matrices
that it passes to a Stan executable to estimate the parameters (without
integrating out the b) via MCMC.
