### ISSUE TITLE
Advice given for diagnosing "BFMI low" doesn't work

### ISSUE THREAD

**Issue by ksvanhorn** [stan-dev/rstan#404]
#### Summary:
Following the advice given for diagnosing "BFMI low" gives an error.

#### Description:
At http://mc-stan.org/misc/warnings.html#bfmi-low it recommends

    Look at the pairs plot to see which primitive parameters are correlated with the energy__ margin.

However, if you do a pairs plot and include 'energy__' in the pars argument to pairs(), you get the message "Error in check_pars(allpars, pars) : no parameter energy__".

#### Reproducible Steps:
pairs(fit, pars=c(x, 'energy__')) for any model parameter x.

#### RStan Version:
2.14.2

#### R Version:
3.3.0

#### Operating System:
Mac OS X 10.12.4 (Sierra)

**Comment by betanalpha** [comment]
Sampler diagnostics are not included in the nominal sampler
output.  You have to retrieve them manually using “get_sampler_params”.
Make sure you extract the nominal sampler output with
 “permuted=FALSE” so that you can align them with the
diagnostics.  See http://mc-stan.org/documentation/case-studies/divergences_and_bias.html <http://mc-stan.org/documentation/case-studies/divergences_and_bias.html>
for an example.

Specifically, the recommendation is to create and analyze the 
pairs plot yourself.  Hopefully all of the sampler output will be
unified in RStan 3 so that the diagnostics are easier to access.

**Comment by ksvanhorn** [comment]
Thanks. The documentation I mentioned should probably include that explanation.

**Comment by bgoodri** [comment]
It is in 2.15.x

**Comment by seantalts** [comment]
+1, I would also like to be able to use the `pairs()` function to diagnose BFMI problems.

**Comment by mdbauer** [comment]
`pairs.stanfit()` adds the `energy__` statistic, but only if no `pars` parameter is provided. It would presumably be simple to change this and to allow for inclusion of the `energy__` statistic in the plot, if it is specified within `pars`. 

Personally I have found it a little cumbersome to set up this pairs-plot by hand.
