### ISSUE TITLE
rstan does not throw sampler warnings when there is just 1 chain

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/rstan#410]
#### Summary:

http://discourse.mc-stan.org/t/rstan-swallows-divergent-transitions/349/7

#### Description:

Only applies when chains = 1 apparently

#### Reproducible Steps:

```
funnel <- stan_demo("funnel", chains = 1, seed = 12345, control = list(adapt_delta = 0.6)) # no warnings
```
#### Current Output:

None

#### Expected Output:

That of
```
rstan:::throw_sampler_warnings(funnel) # warnings
```
#### RStan Version:

2.15.2

#### R Version:

3.4.0

#### Operating System:

Debian

**Comment by helske** [comment]
Wow, just stumbled upon this issue, I have been battling with weird results for a quite some time now due to this. On the `sampling` method, the last lines are

```
 if (chains > 1 && cores <= 1) throw_sampler_warnings(nfit)
   return(nfit)
}
```

and `chains > 1` is obviously `FALSE` here. This seems to be introduced already at the commit d8f996de77c241f8b27a4bee2f404ba667f62143 last September.
