### ISSUE TITLE
In rstan, log_prob != lp__ when using a unit_vector parameter

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/rstan#479]
_From @rgiordan on January 9, 2018 21:47_

#### Summary:
The ```log_prob()``` function in ```rstan``` should return the same value as ```lp__``` from the sampler when called with the parameter values from the same iteration and chain.  But the two differ if (and only if) there is a ```unit_vector``` parameter in the model.

#### Description:
In ```rstan```, one should be able to use ```get_inits```, ```unconstrain_pars```, and ```log_prob``` to get the same value of ```lp__``` as returned from the sampler.  However, the two are not the same if and only if there is a ```unit_vector``` type in the model.

#### Reproducible Steps:
The following R code reproduces the problem for me.  I also included an example without a ```unit_vector``` type to demonstrate expected behavior.  Though not shown, I tried this with every other permissible parameter type and only the ```unit_vector``` has this problem.

```
library(rstan)

good_model_code <- "
data {}
parameters {
  real real_x;
}
model {}
"

bad_model_code <- "
data {}
parameters {
  real real_x;
  unit_vector[2] unit_vector_x;
}
model {}
"

num_chains <- 3
good_model <- stan_model(model_code=good_model_code)
bad_model <- stan_model(model_code=bad_model_code)
good_sampling_result <- sampling(good_model, chains=3, iter=1000, data=list())
bad_sampling_result <- sampling(bad_model, chains=3, iter=1000, data=list())

GetLogProbs <- function(sampling_result, iter, chain) {
  num_warmup_samples <- sampling_result@sim$warmup
  par_list <- get_inits(sampling_result, iter=num_warmup_samples + iter)[[chain]]
  par_free <- unconstrain_pars(sampling_result, par_list)
  
  return(c(
    log_prob(sampling_result, par_free, adjust_transform=TRUE),
    extract(sampling_result, pars="lp__", permute=FALSE)[iter, chain, ]))  
}

# There's nothing special about this iteration and this chain.
iter <- 10
chain <- 2

GetLogProbs(good_sampling_result, iter, chain) # The same
GetLogProbs(bad_sampling_result, iter, chain)  # Not the same
```

#### Current Output:
```
> GetLogProbs(good_sampling_result, iter, chain) # The same
[1] 0 0
> GetLogProbs(bad_sampling_result, iter, chain)  # Not the same
[1] -0.5000000 -0.1071289
```

#### Expected Output:
N/A

#### Additional Information:
I am running rstan (Version 2.17.2, GitRev: 2e1f913d3ca3).

#### Current Version:
v2.17.1

_Copied from original issue: stan-dev/stan#2455_

**Comment by bob-carpenter** [comment]
I just moved this issue here from stan-dev/stan---see link above.

**Comment by bgoodri** [comment]
I believe this is not possible. The value of `target` that you `extract` reflects the actual unconstrained parameters that get normalized into a `unit_vector` by dividing by the square root of their sum of squares. But we cannot uniquely go from a `unit_vector` to the unconstrained space because we do not save the aforementioned denominator. So, the unconstraining function just assumes the denominator is 1.0.

**Comment by bob-carpenter** [comment]
OK, this really is an R issue.  I'll add doc to the manual to explain what's going on (see link above), and I'm closing this because I re-opened the Stan issue (see other link above).

**Comment by rgiordan** [comment]
I see.  Just to make sure I understand -- the Jacobian of the unit vector transform depends on the magnitude of the unconstrainted vector (cf Stan manual 35.7).  But since I'm getting parameter values through `get_init`, which constrains them, the magnitude of the unconstrained space is lost.  When I then run `unconstrain_pars`, it unconstrains with a unit length because the original unconstrained length isn't known.  Since `lp__` includes the Jacobian, which is a function of the non-unit original unconstrained length, it's different than `log_prob(..., adjust_transform=TRUE)` which calculates the Jacobian at a unit length unconstrained vector.

If there were a version of `lp__` that didn't include the Jacobian, it should match  `log_prob(..., adjust_transform=FALSE)`, right?

Is there a way, similar to `get_inits`, to get the unconstrained value at a particular chain and iteration in a form that can be passed to `log_prob`?  It sounds like that information is there.

**Comment by bgoodri** [comment]
That sounds right. I think you would have to save the unconstrained values
to a csv file by specifying the diagnostic_file argument.

**Comment by bob-carpenter** [comment]
Right.  And that leads to a uniform distribution over unit vectors, but it doesn't identify the parameters in the unconstrained space other than through the prior.

If you specify initialization values, nothing changes.  They get converted to unconstrained values and used to initialize.  The Jacobians are still in place.

There isn't a version of `lp__` without the Jacobian.  And there's no way to (easily) get the unconstrained parameters through the language itself, so there's no way to undo the transform.

The information is definitely there under the hood.  We exposed the unconstrained paramters for Andrew at one point, but he never used them.

**Comment by rgiordan** [comment]
Gotcha, thanks for the clear explanation!

FWIW, I don't think this feature per se is critical for me.  I was doing
this to unit test that my R package was correctly evaluating the log
gradient /without/ the Jacboian at the MCMC draws.  Given this description
I think I'm confident that I'm doing the right thing, since it works for
every other parameter type.

It would be really wonderful if it were generally easy to re-run slightly
modified models at all the draws of the original model, possibly with extra
specified parameters, different data, &c.  But I think that would be a
discussion for its own thread.  (Indeed, it probably already has its own
thread somewhere.)
