### ISSUE TITLE
include arguments for distribution functions in rosetta

### ISSUE THREAD

**Issue by kevinushey** [stan-dev/rstan#552]
Currently, functions in the rstan rosetta for distributions are just given `~` as arguments, e.g.:

```R
rosetta <- rstan:::rosetta
rosetta[rosetta$StanFunction == "student_t", ]
#>     RFunction StanFunction Arguments ReturnType Page
#> 612        dt    student_t         ~       real  508
rosetta[rosetta$StanFunction == "inv_gamma", ]
#>     RFunction StanFunction Arguments ReturnType Page
#> 218      <NA>    inv_gamma         ~       real  518
```

Should the arguments accepted by these functions be documented here, as well?

For Stan functions that have a corresponding R function, can I assume the the same arguments are accepted in the same order?

**Comment by bgoodri** [comment]
The `x ~ foo(arg1, arg2) ` statement is essentially equivalent to the function call `foo_lpdf(x | arg1, arg2)`. So, if anything, the arguments to ~ should be the same as the corresponding `_lpdf`. 

But, it is not safe to assume that there is a corresponding R density function, or if so that it has the same parameterization, or if so, that the arguments are in the same order. For example
```
rstan::lookup("^student_t_lpdf")
```
shows that the Student t (log) density is defined in Stan as
```
      StanFunction                                   Arguments ReturnType Page
632 student_t_lpdf (reals y | reals nu, reals mu, reals sigma)       real  115
```
whereas in R
```
args(dt)
```
there is no scale parameter
```
function (x, df, ncp, log = FALSE) 
```

**Comment by kevinushey** [comment]
> The x ~ foo(arg1, arg2) statement is essentially equivalent to the function call foo_lpdf(x | arg1, arg2). So, if anything, the arguments to ~ should be the same as the corresponding _lpdf.

Got it! Thanks for the quick response (and the explanation that parameterization is not necessarily the same even when a Stan function has a corresponding R function)
