### ISSUE TITLE
rstan fails to install under Centos 7

### ISSUE THREAD

**Issue by mkarikom** [stan-dev/rstan#589]
#### Summary:
install.packages('rstan') gives the following error after trying to compile the package:

```
make: *** [lang__ast_def.o] Error 1
ERROR: compilation failed for package ‘rstan’
* removing ‘/home/me/R/x86_64-redhat-linux-gnu-library/3.5/rstan’
```

#### Description:
Based on previous issues reported here, checked that my gcc was sufficient for c++14:
```
[me@here]$ gcc --version
gcc (GCC) 4.9.2 20150212 (Red Hat 4.9.2-6)
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
Here is the content of ~/.R/Makevars:

```
CXX14 = g++
CXX14FLAGS=-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -fPIC
CXX14FLAGS+=-flto -Wno-unused-local-typedefs
```

#### R Version:
```
platform       x86_64-redhat-linux-gnu     
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          5.1                         
year           2018                        
month          07                          
day            02                          
svn rev        74947                       
language       R                           
version.string R version 3.5.1 (2018-07-02)
nickname       Feather Spray               
```
#### Operating System:
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Comment by bgoodri** [comment]
You might need the first line of ~/.R/Makevars to say

CXX14 = g++ -std=c++1y

If that doesn't work, post the full error message when it gets to the
compiler error.

**Comment by alexcombessie** [comment]
Thanks, that worked perfectly for me in a similar setup :)

**Comment by aakbarie** [comment]
I was having similar problems, and it turned out that my header packages (BH and StanHeader) were installed using an older version of g++. Once I installed them using current version of g++ (4.9.2) rstan installed as it should

**Comment by tlyim** [comment]
hello @bgoodri 

I have a similar problem in installing RStan in a cluster provided by another university. I followed your advice above to specify the first line of ~/.R/Makevars:

> **CXX14 = g++ -std=c++1y**
> CXX14FLAGS=-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -fPIC
> CXX14FLAGS+=-flto -Wno-unused-local-typedefs

However, it couldn't avoid the error

> **g++: error: unrecognized command line option ‘-std=gnu++14’**

because **-std=gnu++14** did not go away even with the **-std=c++1y**:

> g++ -std=c++1y **-std=gnu++14** -I"/usr/local/sas/grid/R-3.5.1-linux/include/R"

Both BH and StanHeaders were installed successfully without a problem (so reinstalling BH did not solve this problem). Hope you have a suggestion to solve this problem. Many thanks for your advice. 

Below are the error message, followed by the sessionInfo:

**g++ -std=c++1y -std=gnu++14** -I"/usr/local/sas/grid/R-3.5.1-linux/include/R" -DNDEBUG -I"../inst/include" -I"`"/usr/local/sas/grid/R-3.5.1-linux/lib64/R/bin/Rscript" --vanilla -e "cat(system.file('include', 'src', package = 'StanHeaders'))"`" -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -I"/home/city/sbbg070/R_library/3.5/Rcpp/include" -I"/home/city/sbbg070/R_library/3.5/RcppEigen/include" -I"/home/city/sbbg070/R_library/3.5/BH/include" -I"/home/city/sbbg070/R_library/3.5/StanHeaders/include" -I/usr/local/include   -fpic  -O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -fPIC -flto -Wno-unused-local-typedefs -c chains.cpp -o chains.o
**g++: error: unrecognized command line option ‘-std=gnu++14’**
make: *** [chains.o] Error 1
ERROR: compilation failed for package ‘rstan’
* removing ‘/home/city/sbbg070/R_library/3.5/rstan’
Warning message:
In install.packages("~/rstan_2.18.2.tar.gz", lib = "~/R_library/3.5") :
  installation of package ‘/home/city/sbbg070/rstan_2.18.2.tar.gz’ had non-zero exit status

--------------------------------------------------------------------

> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server 7.6 (Maipo)

Matrix products: default
BLAS: /usr/local/sas/grid/R-3.5.1-linux/lib64/R/lib/libRblas.so
LAPACK: /usr/local/sas/grid/R-3.5.1-linux/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_3.5.1

**Comment by tlyim** [comment]
Hi @bgoodri 

Just had a work around using the following .R/Makevars file:

> CXX14FLAGS=-O3 -march=native -mtune=native -fPIC
> CXX14=g++ -std=c++11
> CXX14FLAGS+= -std=c++11
> **CXX14STD='-std=c++11'**

following hints from 

https://cran.r-project.org/doc/manuals/r-release/R-admin.html#C_002b_002b-Support

**Comment by bgoodri** [comment]
I think just CXX14STD='-std=c++1y' should work now and in the future. Then
you can do `CXX14 = g++` and get rid of the second `CXX14FLAGS` statement.

**Comment by tlyim** [comment]
Thanks for the suggestion, @bgoodri . Tried and confirmed that it works.

**Comment by jonthegeek** [comment]
> CXX14FLAGS=-O3 -march=native -mtune=native -fPIC
> CXX14=g++ -std=c++11
> CXX14FLAGS+= -std=c++11
> **CXX14STD='-std=c++11'**

This (and variations based on the follow-up comment) aren't working for me on CentOS7. I'm installing BH, StanHeaders, and then rstanarm per one of the suggestions above, and each time rstanarm fails despite multiple Makevars tweaks. Anything else it might be?
