### ISSUE TITLE
RStan on Windows with_build_tools problem

### ISSUE THREAD

**Issue by Paul-Yuchao-Dong** [stan-dev/rstan#592]
#### Summary:

After many times of re-installation, I think I finally narrowed it down to the pkgbuild package.

#### Description:
Run into problems when trying to compile stan model with RStan on windows, installation test passed but ran into problem with with_build_tools from pkgbuild package.

I ran into this problem trying to follow along the stan con tutorial [StanCon2018 Helsinki Tutorial](https://github.com/jgabry/stancon2018helsinki_intro)

after crawling thru the issues I noted [this issue](https://github.com/stan-dev/rstan/issues/586) which resonates most.

Also I don't know if this is relavant - I also installed anaconda in my system, which may have changed some environment variables and leads to the wrong compiler being used. I have limited knowledge but I am defintely willing to try all the tests. 

#### Reproducible Steps:
```
library(rstan)
library(inline)
fx <- cxxfunction( signature(x = "integer", y = "numeric" ) , '
	return ScalarReal( INTEGER(x)[0] * REAL(y)[0] ) ;
' )
fx( 2L, 5 )
```
gave the right output.

but 
```
library(pkgbuild)
fx <- with_build_tools(
  cxxfunction( signature(x = "integer", y = "numeric" ) , '
	return ScalarReal( INTEGER(x)[0] * REAL(y)[0] ) ;
' ))
fx( 2L, 5 )
```
gave an error of `Error in eval(substitute(expr), data, enclos = parent.frame()) : is.character(repos) is not TRUE`

#### Current Output:
gave an error of `Error in eval(substitute(expr), data, enclos = parent.frame()) : is.character(repos) is not TRUE`

#### Expected Output:
`[1] 10`

#### RStan Version:
The version of RStan you are running (e.g., from `packageVersion("rstan")`)
2.18.2
#### R Version:
The version of R you are running (e.g., from `R.version.string`)
[1] "R version 3.5.1 (2018-07-02)"
#### Operating System:
Your operating system (e.g., OS X 10.11.3)
Windows 7 64 bit

**Comment by bgoodri** [comment]
I believe you are running into the same problem as https://github.com/r-lib/callr/issues/85 in which case try setting `options(repos = ?)` to a character vector rather than a list. Or install the latest **callr** from GitHub.

**Comment by Paul-Yuchao-Dong** [comment]
@bgoodri Many thanks! I've added this to the initialization cell and now it works!
`options(repos = as.character(getOption("repos")))`
honestly though, I still don't understand what the repos option does and why my computer have a different one than the common / target machine.

**Comment by Seanlove89** [comment]
library(rethinking)
library(rstanarm)
data("reedfrogs")
d <- reedfrogs
# make the tank cluster variable
d$tank <- 1:nrow(d)
# fit


m12.2 <- map2stan(
                   alist(
                     surv ~ dbinom( density , p ) ,
                     logit(p) <- a_tank[tank] ,
                     a_tank[tank] ~ dnorm( a , sigma ) ,
                     a ~ dnorm(0,1) ,
                     sigma ~ dcauchy(0,1)
                   ), data=d , iter=200 , chains=4 )






I am getting an error below

Error in sink(type = "output") : invalid connection
In addition: Warning message:
In system(cmd, intern = !verbose) :
  running command 'C:/PROGRA~1/R/R-36~1.0/bin/x64/R CMD SHLIB file1a90554e2a28.cpp 2> file1a90554e2a28.cpp.err.txt' had status 1
Error in map2stan(alist(surv ~ dbinom(density, p), logit(p) <- a_tank[tank],  : 
  Something went wrong, when calling Stan. Check any debug messages for clues, detective.
invalid connection

#######################################################
The computer is a Lenovo make core i7, v510 series.  Any help is appreciated

I tried to follow comments above but failing because mine has 
Makevars.win.gcc3
