### ISSUE TITLE
New ESS and Rhat with NA in draws

### ISSUE THREAD

**Issue by yao-yl** [stan-dev/rstan#706]
#### Summary:
The current ess_bulk() and Rhat() cannot handle NA appropriately. For instance, it still reports a number even if all draws are NA. 

#### Current Output:
```
> ess_bulk(rep(NA,1000))
[1] 1.303841
> ess_bulk(matrix(NA,1000,2))
[1] 2.267073
> Rhat(matrix(NA,1000,2))
[1] 3.038748
```

#### Expected Output:
```
> ess_bulk(rep(NA,1000))
[1] 0
> Rhat(matrix(NA,1000,2))
[1] Inf
```

#### RStan Version:
2.19.2
#### R Version:
 3.6.1
#### Operating System:
OS X 10.14.6

**Comment by avehtari** [comment]
Thanks for reporting. We should make tests for all edge cases.

**Comment by paul-buerkner** [comment]
After further discussion with Aki, we now prefer the following behavior which I will submit as a PR to rstan soon.

- NA values will result in NA
- inifinite value will result in NaN
- constant values will result in NA

The third is particularily relevant because constant can mean two things: 

(a) logical constant for instance because the parameter is fixed inside the Stan code or because the value is constant because it has to be (i.e., the diagonal of a correlation matrix). This case in unproblematic should not raise any warnings.
(b) the parameter is numerically constant for instance because it did not sample properly or because an indicator variable (as used for quantiles for instance) happens to be all 0 or 1. This case is problematic and should ideally be detected and flagged.

By returning NAs for constant parameters we give the responsibility to check what is going on back to the user who is probably the only one with enough knowledge about the exact reason for the parameter being constant.

See also https://discourse.mc-stan.org/t/ess-rhat-behavior-for-chains-numerical-consistent-with-constants/10465

**Comment by paul-buerkner** [comment]
Just opened a PR that should fix this issue.
