### ISSUE TITLE
the next version of stan will not be able to pre-process your stan program

### ISSUE THREAD

**Issue by rei-lari** [stan-dev/rstan#806]
when I want to use an example for rstan like
fit<- stan(file='schools.stan , data=schools_dat)
this error comes up
"the next version of stan will not be able to pre-process your stan program"
and says to open an issue
what should I do?

**Comment by bob-carpenter** [comment]
As a user, I would be alarmed by the severity of this message.  

Is there a way to make it more specific and suggest a course of correction?  Or is it just a false positive alarm?

**Comment by rok-cesnovar** [comment]
The problem was that rstan 2.21 printed this error even if there was a toolchain error (which was the case most of the time). So yeah, a bunch of false positives.

The situation has now improved in that this error will only be seen if the model compiles with rstan but the stanc3 compilation revealed that it wont compile with stanc3. The message has also since been improved: https://github.com/stan-dev/rstan/pull/795/files

**Comment by jgabry** [comment]
@rei-lari Did this cause the model to not run or did it run ok but also produced the message about the next version not being able to compile it? If it actually prevented you from running the model let us know and we'll help you troubleshoot.

**Comment by jgabry** [comment]
> @bgoodri can we transfer a bunch of these to the rstan repo? Or how do you want to triage these?

Yeah, any of them that are false positives (i.e., any that actually compile fine with stanc3) definitely transfer them over to the rstan repo.

**Comment by bgoodri** [comment]
Just close them if they say the preprocessor did not work. If the
preprocessing works (which it always should if the C++ compiler is found)
and there is an error due to language incompatibility, then it will say
what the error is in the message.
